In [ ]:
## Image Classification using a Convolutional Neural Network and various architectures
## Madeline Quigley
## 2023.04.07

In [1]:
import glob, os, errno
import cv2 as cv
from tensorflow import keras

file = r"C:\Users\Madeline\Documents\Data Mining\Python\Grocery\Weeds\Weed-4class-34\*.jpg"
glob.glob(file)

images = [cv.imread(image) for image in glob.glob(file)]
type(images)
len(images)

3156

In [2]:
import numpy as np
X = []
for filename in glob.glob(file):
    img = cv.imread(filename)
    if img is not None:
     # Resize image
        img = cv.resize(img, (224, 224))
        # Append to list
        X.append(img)
    else:
        print(f"Could not read image: {file}")
trainingSet = np.array(X)
print(trainingSet)

[[[[ 52  60  59]
   [ 49  56  55]
   [ 59  64  62]
   ...
   [ 81  79  75]
   [ 55  54  50]
   [ 38  37  33]]

  [[ 58  66  65]
   [ 61  68  67]
   [ 51  56  55]
   ...
   [ 60  59  55]
   [ 58  57  53]
   [ 47  46  42]]

  [[ 54  62  61]
   [ 59  66  65]
   [ 49  54  52]
   ...
   [ 55  54  50]
   [ 53  52  48]
   [ 40  39  35]]

  ...

  [[225 212 196]
   [154 144 131]
   [186 180 174]
   ...
   [102  91  85]
   [ 81  69  61]
   [ 46  32  25]]

  [[247 233 214]
   [174 162 145]
   [187 180 170]
   ...
   [ 69  58  51]
   [ 87  74  66]
   [ 45  30  23]]

  [[252 237 217]
   [199 186 168]
   [193 184 172]
   ...
   [ 41  30  24]
   [ 74  59  52]
   [ 54  38  31]]]


 [[[ 46  55  59]
   [ 54  66  60]
   [ 47  64  41]
   ...
   [111 102  93]
   [116 106  97]
   [112 101  93]]

  [[ 51  57  61]
   [ 49  61  54]
   [ 58  74  51]
   ...
   [ 89  80  71]
   [ 88  78  70]
   [ 77  66  58]]

  [[ 58  62  66]
   [ 46  55  49]
   [ 53  66  45]
   ...
   [ 85  76  67]
   [ 86  75  67]
   [ 76  65

In [3]:
import numpy as np
import pandas as pd
import numpy as np
import cv2
import glob

# Reading Data
df = pd.read_csv(r"C:\Users\Madeline\Documents\Data Mining\Python\Grocery\Weeds\Weed-4class-34\Weed-4class-34-labels.csv")
file_pattern = r"C:\Users\Madeline\Documents\Data Mining\Python\Grocery\Weeds\Weed-4class-34\*.jpg"

label_list = []

for filename, label in zip(glob.glob(file), df["Species"].tolist()):
    im = cv2.imread(filename)
    # append to list of labels
    label_list.append(label)
    
classifications = np.array(label_list)
print(classifications)

['Chinee apple' 'Chinee apple' 'Chinee apple' ... 'Rubber vine'
 'Rubber vine' 'Rubber vine']


In [4]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
#from tensorflow.keras import layers

#loading data
X_train, X_test, y_train, y_test= train_test_split(X, classifications, test_size=.2)

X_train = np.array(X_train)
X_test = np.array(X_test)

# Scale images to the [0, 1] range
x_train = X_train.astype("float32") / 255
x_test = X_test.astype("float32") / 255

# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
print("x_train shape:", x_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")
print("y_train shape:", y_train.shape)


# Source: https://keras.io/examples/vision/mnist_convnet/

x_train shape: (2524, 224, 224, 3, 1)
2524 train samples
632 test samples
y_train shape: (2524,)


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train_encoded, num_classes=3)
y_test = keras.utils.to_categorical(y_test_encoded, num_classes=3)
print("y_train shape:", y_train.shape)

# Source: https://keras.io/examples/vision/mnist_convnet/

In [ ]:
# CONVOLUTION LAYER WITH 8 3x3 FILTERS

from tensorflow import keras
#from tensorflow.keras import layers

model = keras.Sequential(
    [
        keras.Input(shape=(224,224,3)),
        keras.layers.Conv2D(8, kernel_size=(3, 3), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(3, activation="softmax"),
    ]
)

model.summary()

# Source: https://keras.io/examples/vision/mnist_convnet/

In [ ]:
from tensorflow import keras

batch_size = 128
epochs = 10

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

#model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

# Source: https://keras.io/examples/vision/mnist_convnet/

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

In [ ]:
# CONVOLUTION LAYER WITH 8 3x3 FILTERS

from tensorflow import keras
#from tensorflow.keras import layers

model = keras.Sequential(
    [
        keras.Input(shape=(224,224,3)),
        keras.layers.Conv2D(8, kernel_size=(3, 3), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(3, activation="softmax"),
    ]
)

model.summary()

batch_size = 132
epochs = 10

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

#model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

# Get training and test loss histories
training_accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']

# Create count of the number of epochs
epoch_count = range(1, len(training_accuracy) + 1)

# Visualize loss history
plt.plot(epoch_count, training_accuracy, 'r--')
plt.plot(epoch_count, val_accuracy, 'b-')
plt.legend(['Training Accuracy', 'Validation Accuracy'])
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.show();


# Source: https://keras.io/examples/vision/mnist_convnet/

In [ ]:
# CONVOLUTION LAYER WITH 8 5x5 FILTERS

from tensorflow import keras
#from tensorflow.keras import layers

model = keras.Sequential(
    [
        keras.Input(shape=(224,224,3)),
        keras.layers.Conv2D(8, kernel_size=(5, 5), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(3, activation="softmax"),
    ]
)

model.summary()

batch_size = 132
epochs = 10

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

#model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

# Get training and test loss histories
training_accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']

# Create count of the number of epochs
epoch_count = range(1, len(training_accuracy) + 1)

# Visualize loss history
plt.plot(epoch_count, training_accuracy, 'r--')
plt.plot(epoch_count, val_accuracy, 'b-')
plt.legend(['Training Accuracy', 'Validation Accuracy'])
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.show();


# Source: https://keras.io/examples/vision/mnist_convnet/

In [ ]:
# CONVOLUTION LAYER WITH 8 7x7 FILTERS

from tensorflow import keras
#from tensorflow.keras import layers

model = keras.Sequential(
    [
        keras.Input(shape=(224,224,3)),
        keras.layers.Conv2D(8, kernel_size=(7, 7), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(3, activation="softmax"),
    ]
)

model.summary()

batch_size = 132
epochs = 10

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

#model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

# Get training and test loss histories
training_accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']

# Create count of the number of epochs
epoch_count = range(1, len(training_accuracy) + 1)

# Visualize loss history
plt.plot(epoch_count, training_accuracy, 'r--')
plt.plot(epoch_count, val_accuracy, 'b-')
plt.legend(['Training Accuracy', 'Validation Accuracy'])
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.show();


# Source: https://keras.io/examples/vision/mnist_convnet/